import { createClient } from '@supabase/supabase-js'

export const supabase = createClient('https://cjlwbrfycwtwmbcqvjpn.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqbHdicmZ5Y3d0d21iY3F2anBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwNDAzNjgsImV4cCI6MjA1NjYxNjM2OH0.srowqiDo1d2TJrSBJYJYsnFySRF_8iDMCotV1kiErIw')